### ISSUE TITLE
Failed to unlink errors

### ISSUE THREAD

**Issue by scaraux** [georstat/react-native-image-cache#31]
Using the following config:

```
  CacheManager.config = {
    baseDir: `${Dirs.CacheDir}/images_cache/`,
    blurRadius: 15,
    cacheLimit: 1024 * 1024 * CACHE_SIZE_LIMIT_MB,
    sourceAnimationDuration: 500,
    thumbnailAnimationDuration: 0,
  };
```

I get a ton of errors like below, and notice some stuff gets evicted when it should not (cache size way below cache limit)

```
[Error: Failed to unlink '/Users/myuser/Library/Developer/CoreSimulator/Devices/044AF9EB-4BC2-45E0-8C2D-F51B91B355DD/data/Containers/Data/Application/3E25A477-CA0B-46B5-ADEB-C400AFC8B7AC/Library/Caches/images_cache/7f5452e0d26c3b51449671d559bff25da96b95ba.jpg'.]
```

```
[Error: Failed to list '/Users/myuser/Library/Developer/CoreSimulator/Devices/044AF9EB-4BC2-45E0-8C2D-F51B91B355DD/data/Containers/Data/Application/3E25A477-CA0B-46B5-ADEB-C400AFC8B7AC/Library/Caches/images_cache/'.]
```

When I remove the trailing `/` from the `baseDir`, it stops doing these errors. However, if I now try to do a `CacheManager.clearCache()`, it will have an invalid path. (missing trailing `/`)

Versions:
`"@georstat/react-native-image-cache": "^2.2.0"`
`"react-native-file-access": "^2.4.3"`

**Comment by scaraux** [comment]
Further debugging, there seems to be some race concurrency where multiple pruning happens at the same time and multiple files are attempted to be unlinked at the same time.

**Comment by geobako** [comment]
Hi @scaraux ,

I would suggest the obvious at first: delete node modules and pods as well as all the emulator data and see if the error persists. Does it also happen in android? Does it happen with file access 2.4.0? If none of the solutions work, then we will need to debug it further.

**Comment by efstathiosntonas** [comment]
@scaraux it’s not a racing condition, every time an image is downloaded we check the cache if it has hit it’s limit, I don’t think there’s a better way but of course we’re here to discuss and we’re open on PRs.

 The only race condition would be to have many images being downloaded at the same time so there would be a “first downloaded-first deleted” since that image could be the oldest one in the queue and the prune function deleted it. (I hope that was clear enough)

Personally I have never encountered these errors on my social app (with thousands of images being cached). The only time this occurred was when I mistakenly had really small `cacheLimit` value, then I increased the limit in the config and instead of doing a full refresh of the app I just curried on with fast refresh, this flow threw the exact same errors like yours.

**Comment by scaraux** [comment]
I was mentioning the concurrency as i see that its attempting to prune multiple times the same file, and the first time is successfull and the other times cause the failed to unlink log.

Will try with 2.4.0 when I get the chance. And i don't have a small cache limit as shown above.

**Comment by scaraux** [comment]
I downgraded to 2.4.0 and still getting the error. The trailing `/` on the baseDir causes all the issues. Removing it works. But if I remove it, all `CacheManager` calls that I write will now fail.

**Comment by efstathiosntonas** [comment]
@scaraux if you increase the cache size to 50MB does it behave the same?

**Comment by scaraux** [comment]
@efstathiosntonas yes it does

**Comment by efstathiosntonas** [comment]
@scaraux tried to replicate the issue, see attached video, can you create a video like a did and try to replicate the issue?

https://youtu.be/s_zN_wlY7mI

**Comment by efstathiosntonas** [comment]
@scaraux I believe what is happening in your case is:

1. Small Cache Limit to start with let's say 15MB for example
2. You try to download eg 10 images on a FlatList, the size of these images are 50MB in total (for example), each one 5MB
3. CacheManager downloads 3 images, we've reached the CacheLimit
4. While the rest of them (7 images) are being downloaded we enter in a race condition as described [here](https://github.com/georstat/react-native-image-cache/issues/31#issuecomment-1169090122)  (2nd paragraph).

The 1st downloaded image from step 4 will trigger a prune and delete the oldest image while on the same time the 2nd image in the queue will initiate a prune too on the oldest image. What could be happening in this scenario is:
 
low effort to somehow visualise the flow:

cacheLimit: 15MB

Step A:
start download... :
1. image.jpg 5MB date: 1 (oldest)
2. image2.jpeg 5MB date: 2
3. Image3.jpeg 5MB date: 3 (newest)

Step B:
cacheLimit reached, `image4.jpeg 5MB date: 4` is incoming:
1. ~image.jpg date: 1~ is deleted (oldest)
2. image2.jpeg date: 2 
3. image3.jpeg date: 3(newest)
4. image4.jpeg date: 4 takes image.jpeg place  (this is the newest now)

Step C happening in parallel with Step B:
At the same time in parallel `image5.jpeg 5MB date: 5` is incoming:
1. ~image2.jpeg date: 2~ is deleted (oldest)
2. image3.jpeg date: 3
3. image4.jpeg date: 4 (newest)
4. image5.jpeg date: 5 takes image2.jpeg place  (this is the newest now)


What I believe is happening here is that Step C tries to delete `image.jpg date:1` from Step B since Step A & B are happening in parallel and C is finishing it's job before B.

I'm open to ideas on how to fix that even though I think it's not possible. On the other hand we have[ this check prior deleting a file](https://github.com/georstat/react-native-image-cache/blob/17d0aa8e3cdf9f4b7f754c75eeb8cafb4c15c2c6/src/CacheManager.ts#L189) witch should stop the deletion and do not throw an `unlink error`. Will investigate if this check works well or not and come back with results if any.

@geobako

**Comment by unstoo** [comment]
@efstathiosntonas 
Hello! Thank you for the amazing library!

I'm having somewhat similar 'unlink' problem within my app. I have a live chat that supports images. When I receive lots of incoming images and the cache hits the limit I get a bunch of 'unlink' errors. In addition, occasionally because of it react native may end up not rendering an image component within a SectionList at all.

So far the only workaround that came to my mind, is to exclude `pruneCache` from the `download` method, and run it once on the initial load of the app. Have you considered this approach? Any pitfalls to be aware of?

Thanks!

**Comment by szymon-rajewski** [comment]
I have the same problem. Can you reopen issue? @efstathiosntonas
