### ISSUE TITLE
Is this different from FastImage and does this lib support Fabric?

### ISSUE THREAD

**Issue by Miraj98** [georstat/react-native-image-cache#35]
Just had two questions 
1. Can this library act as replacement for react-native-fast-image and if there are any benchmarks available to compare the two?
2. Is this library compatible with the new Fabric renderer?

**Comment by geobako** [comment]
Hello @Miraj98 ,

FastImage saves images on memory so it is quite faster. We just noticed high memory consumption when we needed images at full resolution and decided to create this library so that we save images on the file system and have a little more control over caching. So it really depends on the use case.

This library depends on reanimated and react-native-file-access so whether or not we support fabric depends on these libraries

**Comment by Miraj98** [comment]
Oh, so react-native-image-cache does not support Fabric, got it. Reanimated supports Fabric in v3 btw.
Is there an active effort or a PR that is trying to port the library to Fabric?
I don't mind starting an issue on react-native-file-access if one is not already there that is tracking progress for Fabric.

**Comment by efstathiosntonas** [comment]
@Miraj98 as @alpha0010 stated `react-native-file-access` will support Fabric in the future, closing this now.
