### ISSUE TITLE
error: SyntaxError: /Users/.../Projects/.../node_modules/@georstat/react-native-image-cache/src/CachedImage.tsx: Unexpected token, expected ")" (120:16)

### ISSUE THREAD

**Issue by alexkendall** [georstat/react-native-image-cache#40]
Getting this compilation error with the latest version.

error: SyntaxError: /Users/.../Projects/.../node_modules/@georstat/react-native-image-cache/src/CachedImage.tsx: Unexpected token, expected ")" (120:16)

**Comment by efstathiosntonas** [comment]
Hi @alexkendall, there’s no “)” on [line 120](https://github.com/georstat/react-native-image-cache/blob/bee2b26784cd8aa193e6a8609192181d8af3919f/src/CachedImage.tsx#L120) that could cause syntax error.

besides that, it’s bot possible for us to ship bad syntax on npm since we build the code prior publishing. 

Can you please make sure you haven’t touched anything on that file? (also check if you have a `patch-package` file for this module)

**Comment by efstathiosntonas** [comment]
@alexkendall closing the issue, if you’re still getting error let us know.
