### ISSUE TITLE
● Test suite failed to run      Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by Sahand-Stefan** [georstat/react-native-image-cache#46]
I am facing issue in this dependency while running tests with jest

**Comment by Sahand-Stefan** [comment]
● Test suite failed to run

    Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

      1 | import React from "react"
      2 | import { Image, ImageStyle, ImageResizeMode, ImageBackground } from "react-native"
    > 3 | import { CachedImage } from "@georstat/react-native-image-cache"
        | ^
      4 | import { EnumImageType } from "@app/constants"
      5 |
      6 | interface LActImageProps {

**Comment by efstathiosntonas** [comment]
Hi @Sahand-Stefan, it seems the issue comes from `react-native-file-access`, it's using `NativeEventEmitter` as seen [here](https://github.com/alpha0010/react-native-file-access/blob/2c9775ba4d95b53df361d8295a4572f5cb5055ca/src/native.ts#L11)

Please open an issue on that repo and reference this issue here.

**Comment by Sahand-Stefan** [comment]
@efstathiosntonas 

Yes Thanks, I mocked it like this and is working now:

`jest.mock("@georstat/react-native-image-cache", () => ({
  source: "",
  CacheManager: {
    config: {},
  },
}))`

**Comment by efstathiosntonas** [comment]
Great, glad you found a solution!
